name: Test if cookiecutter runs without issue

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: cookiecutter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install cookiecutter
      run: uv tool install cookiecutter
    - name: Test if cookiecutter works 
      run: |
        cookiecutter --no-input .
